# Generated by Django 3.2.9 on 2021-12-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
