# Generated by Django 3.2.9 on 2021-12-15 11:39

import django.core.validators
from django.db import migrations, models
import thumbnailerist.thumbnail


class Migration(migrations.Migration):

    dependencies = [
        ('pizzap', '0002_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='photo',
            field=models.ImageField(null=True, upload_to=thumbnailerist.thumbnail.get_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to=thumbnailerist.thumbnail.get_file_name),
        ),
    ]
